// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

//	type Todo {
//	  id: ID!
//	  text: String!
//	  done: Boolean!
//	  user: User!
//	}
//
//	type User {
//	  id: ID!
//	  name: String!
//	}
//
//	type Query {
//	  todos: [Todo!]!
//	}
//
//	input NewTodo {
//	  text: String!
//	  userId: String!
//	}
//
//	type Mutation {
//	  createTodo(input: NewTodo!): Todo!
//	}
type Link struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Address string `json:"address"`
	User    *User  `json:"user"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewLink struct {
	Title   string `json:"title"`
	Address string `json:"address"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Query struct {
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
